export const posts = [
    {
        id: 1,
        title: 'Emphysema',
        href: '',
        description: 'Emphysema is characterized by permanently enlarged airspaces distal to the terminal bronchiole, with destruction of alveolar walls. Emphysema is usually classified according to the part of the acinus predominantly affected. The Computed Tomography appearance of emphysema consists of focal areas or regions of low attenuation, usually without visible walls.',
        imageUrl: '/emphysema.png',
        category: {title: 'Lung'},
    },
    {
        id: 2,
        title: 'Airway disease - Bronchial Wall Thickening',
        href: '#',
        description: 'Bronchial wall thickening is an imaging descriptor used to describe abnormal thickening of bronchial walls and can arise from a vast number of pathological entities. ' +
            'It is one of the causes of peribronchial cuffing. The presence of bronchial wall thickening usually implies inflammation of the airways.',
        imageUrl: '/bronchialwall.png',
        category: {title: 'Lung'},
    },
    {
        id: 3,
        title: 'Airway disease - Bronchiectasis',
        href: '#',
        description: 'Irreversible localized or diffuse bronchial dilatation, usually resulting from chronic infection, proximal airway obstruction, or congenital bronchial abnormality.',
        imageUrl: '/bronchiectasis.png',
        category: {title: 'Lung'},
    },
    {
        id: 4,
        title: 'Airway disease - Centrilobular nodules',
        href: '#',
        description: 'Rounded or irregular opacity, well or poorly defined, measuring up to 3 cm in diameter. Centrilobular nodules appear separated by several millimeters from the pleural surfaces, fissures, and interlobular septa. They usually are ill-defined, with soft-tissue or ground-glass attenuation, and size ranging from a few millimeters to one centimeter.',
        imageUrl: '/centrilobular.png',
        category: {title: 'Lung'},
    },
    {
        id: 5,
        title: 'Airway disease - Air trapping',
        href: '#',
        description: 'Air trapping represents the retention of air in the lung distal to an obstruction. Air trapping is best evaluated on end-expiration CT scans as parenchymal areas with less than normal increase in attenuation and lack of volume reduction. Comparison between inspiratory and expiratory CT scans is helpful when air trapping is subtle or diffuse. Differentiating air trapping from lung parenchymal mosaic perfusion is a major challenge when interpreting end-inspiratory CT images.',
        imageUrl: '/trapping.jpg',
        category: {title: 'Lung'},
    },
    {
        id: 6,
        title: 'Lung fibrosis',
        href: '#',
        description: 'Lung fibrosis can be qualitatively graded into three levels: 0-10%, 11-30%, and > 30%. Usual interstitial pneumonia (UIP) and nonspecific interstitial pneumonia (NSIP) are the main CT patterns of lung fibrosis.',
        imageUrl: '/fibrosis.png',
        category: {title: 'Lung'},
    },
    {
        id: 7,
        title: 'Centrilobular ground-glass nodules',
        href: '#',
        description: 'Nodules with centrilobular distribution locate a few millimeters away from the pleural surface and fissures, without direct contact with them. Diffusely distributed, poorly defined centrilobular ground-glass nodules are commonly observed in patients with idiopathic PAH. These nodules correspond to cholesterol granulomas resulting from the ingestion of red blood cells by pulmonary macrophages [65]. The differential diagnosis includes hypersensitivity pneumonitis, respiratory bronchiolitis, follicular bronchiolitis, and long-standing left-to-right shunt. It is worth noting that centrilobular ground-glass nodules, along with tortuous corkscrew vessels, can also be observed in pulmonary capillary hemangiomatosis (PCH) and pulmonary veno-occlusive disease (PVOD).',
        imageUrl: '/ground.png',
        category: {title: 'Lung'},
    },
    {
        id: 8,
        title: 'Mosaic attenuation pattern',
        href: '#',
        description: 'This pattern appears as patchwork of regions of differing attenuation that may represent (a) patchy interstitial disease, (b) obliterative small airways disease, or (c) occlusive vascular disease. CT features suggesting vascular origin include signs of primary PH, chronic pulmonary embolism, and PVOD.',
        imageUrl: '/mosaic.png',
        category: {title: 'Lung'},
    },
    {
        id: 9,
        title: 'Left atrium enlargement',
        href: '#',
        description: 'The diameter measurements of the left atrium on CT axial images should be determined as the largest anterior-posterior diameter. It is a continuous, metric variable.',
        imageUrl: '/left_atrium.png',
        category: {title: 'Heart'},
    },
    {
        id: 10,
        title: 'Coronary artery calcification ',
        href: '#',
        description: 'Coronary artery calcification can be identified as high-attenuation material in the path of a coronary artery. For non-gated thoracic CT in routine clinical practice, it is recommended to use a simple visual ordinal score performed on a whole-patient basis. CAC is scored as absent, mild, moderate, or severe on a whole-patient basis to summarize the cumulative findings in all the coronary arteries. This approach can be applied to both non-contrast and contrast-enhanced images.',
        imageUrl: '/coronary_artery.png',
        category: {title: 'Heart'},
    },
    {
        id: 11,
        title: 'Valvular calcification',
        href: '#',
        description: 'Valvular calcification can be identified as high-attenuation material in the region of the aortic valve. Care should be taken to differentiate valve calcification from calcification in the aortic root, mitral annulus, or coronary arteries (aortic valve).',
        imageUrl: '/valvular_calcification.png',
        category: {title: 'Heart'},
    },
    {
        id: 12,
        title: 'Congenital heart disease',
        href: '#',
        description: 'The pathophysiology of congenital heart disease is variable and complex, affecting management decisions. In patients with large shunts, pulmonary vascular disease develops secondary to shear stress, endothelial damage, smooth muscle proliferation, remodeling of the vasculature, and ultimately obliteration of the microvasculature, similar to idiopathic PAH.',
        imageUrl: '/congenital_heart.png',
        category: {title: 'Heart'},
    },
    {
        id: 13,
        title: 'Chronic thromboembolic pulmonary disease',
        href: '#',
        description: 'Main CTEPH findings include: vascular obstruction; lung hyperemia; collateral systemic supply and peripheral scars.',
        imageUrl: '/ctph.png',
        category: {title: 'Pulmonary vessels'},
    },
    {
        id: 14,
        title: 'Enlarged lymph nodes',
        href: '#',
        description: 'Cut off of 10 mm has been conventionally used to define an enlarged lymph node.',
        imageUrl: '/lymph_nodes.jpg',
        category: {title: 'Mediastinum'},
    },
    {
        id: 15,
        title: 'Esophageal dilatation',
        href: '#',
        description: 'Axial diameter cutoff value of 10 mm at the carinal level or 15 mm as maximum diameter.',
        imageUrl: '/esophageal.png',
        category: {title: 'Mediastinum'},
    },
    {
        id: 16,
        title: 'Signs of portal hypertension',
        href: '#',
        description: 'Presence of enlarged portosystemic collateral vessels in the chest and upper abdomen. Coronary venous collaterals are typically associated with esophageal or paraesophageal varices. Esophageal varices are commonly fed by the anterior branch of the left gastric vein, while the posterior branch of this vein supplies paraesophageal varices. On CT, varices are distinct, round, tubular, or winding structures that exhibit smooth, homogeneous attenuation and enhance with contrast material to a similar degree as neighboring portal and mesenteric veins.',
        imageUrl: '/portal_hypertension.png',
        category: {title: 'Mediastinum'},
    },
];