[[redirects]]
from = "/*"
to = "src/app/PageNotFound/Error-page.jsx"
status = 404

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/home"
to = "src/app/diagnosis/Diagnosis.jsx"
status = 301