[[redirects]]
from = "/*"
to = "src/app/PageNotFound/Error-page.jsx"
status = 404

[[redirects]]
from = "/home"
to = "/Root.jsx"
status = 200

[[redirects]]
from = "/groups"
to = "/Groups.jsx"
status = 200

[[redirects]]
from = "/about"
to = "/AboutUs.jsx"
status = 200

[[redirects]]
from = "/findings"
to = "/Findings.jsx"
status = 200

[[redirects]]
from = "/diagnosis"
to = "/Diagnosis.jsx"
status = 200